[[playlist_collections]]
id = "default"
playlists = [ "smoothjazz", "deutschlandfunk", "hr1" ]

[[playlist_collections]]
id = "otherCollection"
playlists = [ "smoothjazz", "deutschlandfunk", "hr3" ]

[[mpds]]
name = "living-room"
address = "myserver"
port = 6605
playlist_collection_id = "default"

[[mpds]]
name = "bath-upstairs"
address = "127.0.0.1"
port = 6601
playlist_collection_id = "default"

[[mpds]]
name = "bath-downstairs"
address = "::1"
port = 6602
playlist_collection_id = "otherCollection"
